[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'php82Extensions.mbstring', 'php82Extensions.zip', 'php82Extensions.gd', 'nginx', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction',
    'npm ci --production=false'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf'
